# Site settings
title: Andreas Öhlund
email: andreas.ohlund@particular.net
description: > # My thoughts on Software Development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreasohlund.net" # the base hostname & protocol for your site
twitter_username: andreasohlund
github_username:  andreasohlund
permalink:    /:year/:month/:day/:title/

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
