# Site settings
title: My thoughts on software development
email: andreas.ohlund@particular.net
description: > # Random rambling on stuff I come across as a Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreasohlund.net" # the base hostname & protocol for your site
twitter_username: andreasohlund
github_username:  andreasohlund

# Build settings
markdown: kramdown
